language: cpp

os: linux
dist: bionic
compiler: gcc
script: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel && ./Hello 
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Hello
  skip_cleanup: true
  draft: true


#jobs:
#  include:
#   - name: "Ubuntu 18.04"
#     os: linux
#     dist: bionic
#     compiler: gcc
#     script: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel && ./Hello 
#     deploy:
#       - name: Ubuntu deploy
#         provider: releases
#         api_key: "GITHUB OAUTH TOKEN"
#         file:
#            - Hello
#         skip_cleanup: true
#         draft: true
#         #prerelease: true
#         #on:
#         #   tags: true
#
#   - name: "Windows"
#     os: windows
#     script: 
#       - cmd //c "cmake . & cmake --build . --config Release --target Hello --parallel & .\Release\Hello.exe"
#     deploy:
#       - name: Windows deploy
#         provider: releases
#         api_key: "GITHUB OAUTH TOKEN"
#         file:
#            - Release\Hello.exe
#         skip_cleanup: true
#         draft: true
#         #prerelease: true
#         #on:
#         #   tags: true
#