language: cpp

# https://github.com/electron-userland/electron-builder/issues/3559
if: tag IS blank

jobs:
  include:
   - name: "Ubuntu 18.04"
     os: linux
     dist: bionic
     compiler: gcc
     script: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel && ./Hello 
     before_install:
         # https://github.com/electron-userland/electron-builder/issues/3559
       - export TRAVIS_TAG="autotagname"
     deploy:
       - provider: releases
         #name: ${TRAVIS_TAG}
         tag_name: ${TRAVIS_TAG}
         api_key: ${GITHUB_TOKEN}
         file:
            - Hello
         skip_cleanup: true
         overwrite: true
#         draft: true
         prerelease: true
#         on:
#            tags: true

   - name: "Windows"
     os: windows
     script: 
       - cmd //c "cmake . & cmake --build . --config Release --target Hello --parallel & .\Release\Hello.exe"
     before_install:
         # https://github.com/electron-userland/electron-builder/issues/3559
       - export TRAVIS_TAG="autotagname"
     deploy:
       - provider: releases
         #name: ${TRAVIS_TAG}
         tag_name: ${TRAVIS_TAG}
         api_key: ${GITHUB_TOKEN}
         file:
            - Release\Hello.exe
         body: "    One paragraph only"
         skip_cleanup: true
         overwrite: true
#         draft: true
         prerelease: true
#         on:
#            tags: true
