on: [push, pull_request]
jobs:
 # This job may be commented if a new release should not be created...
 deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: autotagname-${{ github.sha }}
        release_name: autotagname-${{ github.sha }}
      if: github.event_name != 'pull_request'
 build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            python-version: [3.8]
            include:
            - os: ubuntu-latest
              deploy-file: ./Hello
            - os: windows-latest
              shell: bash
              deploy-file: ./Debug/Hello.exe
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        cmake . && cmake --build .
        python -c "import sys; print(sys.version)"
        ls -l
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "${{ matrix.deploy-file }}"
        overwrite: true
        tag_name: autotagname-${{ github.sha }}
      if: github.event_name != 'pull_request'
